version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: docchat-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"  # gRPC port
    volumes:
      - ./qdrant_storage:/qdrant/storage
      - ./qdrant_config:/qdrant/config
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - docchat-network

  # Optional: Qdrant Web UI for debugging
  qdrant-ui:
    image: qdrant/qdrant-web-ui:latest
    container_name: docchat-qdrant-ui
    ports:
      - "6335:3000"
    environment:
      - QDRANT_URL=http://qdrant:6333
    depends_on:
      - qdrant
    networks:
      - docchat-network
    profiles:
      - debug

networks:
  docchat-network:
    driver: bridge

volumes:
  qdrant_storage:
    driver: local
  qdrant_config:
    driver: local